POST http://localhost:4000/register 
Content-Type: application/json

{
    "username": "malikaii",
    "email": "love@gmail.com",
    "password": "yes345"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
    "username": "malikaii",
    "password": "yes345"
}